### PR TITLE
fix radial plot scaling & group order

### PR DESCRIPTION
**Pull request by tanerumit**

### CODE REVIEW

**Comment by grijzea** [comment]
approved

**Comment by grijzea** [comment]
merge

**Comment by grijzea** [comment]
approved

**Comment by grijzea** [comment]
merge to main

**Comment by grijzea** [comment]
test

**Review by grijzea — APPROVED** [review]

**Comment by Carsopre** [comment]
@grijzea this should have not been added without the test bench going green.

**Pull request merged**
